import * as paramTypes from '../types/KnowledgebaseTypes';
import { Connection, XmlmcResponse } from '../Connection';
import Xmlmc from '../XmlMethodCall';
export declare class Knowledgebase {
    private connection;
    private xmlmc;
    private service;
    private paramMap;
    constructor(connection: Connection, xmlmc: Xmlmc);
    articleAdd(title: string, docVisibleToCustomers: boolean, docStatus: Object, catalogId: Object, optionalParams?: paramTypes.articleAddParams): Promise<XmlmcResponse>;
    articleDelete(docRef: string, optionalParams?: paramTypes.articleDeleteParams): Promise<XmlmcResponse>;
    articleUpdate(docRef: string, optionalParams?: paramTypes.articleUpdateParams): Promise<XmlmcResponse>;
    catalogAdd(name: string, optionalParams?: paramTypes.catalogAddParams): Promise<XmlmcResponse>;
    catalogDelete(catalogId: number, optionalParams?: paramTypes.catalogDeleteParams): Promise<XmlmcResponse>;
    catalogList(optionalParams?: paramTypes.catalogListParams): Promise<XmlmcResponse>;
    catalogRename(catalogId: number, newName: string, optionalParams?: paramTypes.catalogRenameParams): Promise<XmlmcResponse>;
    documentAdd(title: string, docVisibleToCustomers: boolean, docStatus: number, catalogId: number, document: Object, optionalParams?: paramTypes.documentAddParams): Promise<XmlmcResponse>;
    documentAddChange(docRef: string, date: Date, optionalParams?: paramTypes.documentAddChangeParams): Promise<XmlmcResponse>;
    documentClearChanges(docRef: string, optionalParams?: paramTypes.documentClearChangesParams): Promise<XmlmcResponse>;
    documentDelete(docRef: string, optionalParams?: paramTypes.documentDeleteParams): Promise<XmlmcResponse>;
    documentFlagForModification(docRef: string, optionalParams?: paramTypes.documentFlagForModificationParams): Promise<XmlmcResponse>;
    documentGetCallref(docRef: string, optionalParams?: paramTypes.documentGetCallrefParams): Promise<XmlmcResponse>;
    documentGetChanges(docRef: string, optionalParams?: paramTypes.documentGetChangesParams): Promise<XmlmcResponse>;
    documentGetInfo(docRef: string, optionalParams?: paramTypes.documentGetInfoParams): Promise<XmlmcResponse>;
    documentGetRelated(docRef: string, optionalParams?: paramTypes.documentGetRelatedParams): Promise<XmlmcResponse>;
    documentGetSurveyAverageUsefulness(docRef: string, optionalParams?: paramTypes.documentGetSurveyAverageUsefulnessParams): Promise<XmlmcResponse>;
    documentGetType(docRef: string, optionalParams?: paramTypes.documentGetTypeParams): Promise<XmlmcResponse>;
    documentGetUrl(docRef: string, optionalParams?: paramTypes.documentGetUrlParams): Promise<XmlmcResponse>;
    documentIncreaseAccessCounter(docRef: string, optionalParams?: paramTypes.documentIncreaseAccessCounterParams): Promise<XmlmcResponse>;
    documentList(optionalParams?: paramTypes.documentListParams): Promise<XmlmcResponse>;
    documentSetRelated(docRef: string, optionalParams?: paramTypes.documentSetRelatedParams): Promise<XmlmcResponse>;
    documentSetSurveyInfo(docRef: string, analystID: string, groupID: string, usefulness: Object, optionalParams?: paramTypes.documentSetSurveyInfoParams): Promise<XmlmcResponse>;
    documentUpdate(docRef: string, optionalParams?: paramTypes.documentUpdateParams): Promise<XmlmcResponse>;
    doesFileExist(fileName: string, optionalParams?: paramTypes.doesFileExistParams): Promise<XmlmcResponse>;
    isCallInKnowledgeBase(callref: string, optionalParams?: paramTypes.isCallInKnowledgeBaseParams): Promise<XmlmcResponse>;
    queryKeyword(queryString: string, queryType: string, optionalParams?: paramTypes.queryKeywordParams): Promise<XmlmcResponse>;
    queryNatural(queryString: string, optionalParams?: paramTypes.queryNaturalParams): Promise<XmlmcResponse>;
    templateList(optionalParams?: paramTypes.templateListParams): Promise<XmlmcResponse>;
    unpublishedCallAdd(callRef: number, optionalParams?: paramTypes.unpublishedCallAddParams): Promise<XmlmcResponse>;
    unpublishedCallDelete(callRef: number, optionalParams?: paramTypes.unpublishedCallDeleteParams): Promise<XmlmcResponse>;
    unpublishedCallList(optionalParams?: paramTypes.unpublishedCallListParams): Promise<XmlmcResponse>;
}
